### ISSUE TITLE
Nix install not working with newest version of Nix

### ISSUE THREAD

**Issue by TitusCornelius** [wavewave/hoodle#45]
hey,

maybe I am an idiot, but I spent quite some time trying to install Hoodle with nix on the most recent version of Nix and Ubuntu. There does not seem to be a way to do it, which is really unfortunate. The semester has just started and I would really like to use Hoodle instead of Xournal (I really love learning with digital notebooks and I am dissatisfied with any other program) and I don't know what to do to get it working. Should I just run an older Linux distro in a virtual machine?

Any help (preferably a bit more spelled out for a newbie) would be highly appreciated! Sorry for the repeated bugging..

thanks in advance,
Titus

`$ nix-env -qa *hoodle*`
`error: selector ‘hoodle’ matches no derivations`

and installing from inside a cloned github repo also does not seem to be an option with Nix

**Comment by wavewave** [comment]
sorry to hear that the current nix installation does not work now. Let me look into the problem. One complication in your case is that you are using nix on Ubuntu, which should work well, but recently there have been some issues (hopefully things may have been already sorted out. ) Get back here soon after checking nix installation.

**Comment by wavewave** [comment]
These days, haskell packages are installed in a different way, no more `nix-env -i` installation, but using some shell environment by writing some nix expression file (which unfortunately is quite difficult for novice nix users.). 
More desirably, we should classify hoodle executable as a standalone application rather than a haskell package. I am going to repackage hoodle as an application in nixpkgs, while remaining other dependencies of hoodle (such as hoodle-core, hoodle-render and so on) as haskell packages.
