### ISSUE TITLE
Generalize config file parsing

### ISSUE THREAD

**Issue by rpglover64** [wavewave/hoodle#52]
Helps with #51 

The [`ini`](https://hackage.haskell.org/package/ini), [`ConfigFile`](https://hackage.haskell.org/package/ConfigFile), and [`configurator`](https://hackage.haskell.org/package/configurator) libraries provide generic config file parsing in Haskell. `configurator` is further documented in a [24 days of hackage](https://ocharles.org.uk/blog/posts/2012-12-21-24-days-of-hackage-configurator.html) post, and the other two options open the possibility of compatibility with xournal config files.

Feel free to tell me to stop submitting issues.

**Comment by wavewave** [comment]
Currently, `hoodle` depends on [`configurator`](https://hackage.haskell.org/package/configurator). `.hoodle` file in the `$HOME` directory is parsed by the `configurator` library. So I think this issue is not valid. 

If we want to have some good grammar and documentation on configuration file, let's make a separate issue. 

I am very happy to have your active suggestions and discussion. Please do not hesitate submitting any  kind of issues and bug reports.
