### ISSUE TITLE
Error In the dependencies for svgcairo

### ISSUE THREAD

**Issue by nh-3** [wavewave/hoodle#65]
Hello there.

I'm stuck at this point.

```
$ stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for svgcairo-0.13.1.2:
    gtk2hs-buildtools-0.13.3.1 from stack configuration does not
                               match >=0.13.11 && <0.14 
needed due to hoodle-core-0.16.0 -> svgcairo-0.13.1.2

```
I don't how to solve the dependencies.

I tried this first solution:
```
Some different approaches to resolving this:

  * Set 'allow-newer: true'
    in ~/.stack/config.yaml to ignore all version constraints and build anyway.
```

but after editing that, I've got this:
```
$ stack build
Could not parse '~/.stack/config.yaml':
YAML parse exception at line 14, column 0,
while scanning for the next token:
found character that cannot start any token
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

###########################################
              Fedora 29

**Comment by matt-chan** [comment]
You were closer to the solution in the first post. Instead of editing the global stack.yaml, you need to edit the one in the project sources. Also, it just looks like you got a syntax error in the yaml, not an actual error in the build. 

I managed to get it to build eventually on RHEL7. There's a _lot_ of devel packages missing for the C dependencies (which stack doesn't warn about...).
